<a href="https://colab.research.google.com/github/Harsha-7989/TensorFlow/blob/main/TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  Introduction to Tensors
  * Getting infromation to tensors
  *  Manipulating tensors
  *  Tensors and Numpy
  * Using @tf.function (a way to speed up your regular python functions)
  * Using GPUs with Tensorflow (OR TPUs)


Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [4]:
# Creating the Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
 # check the dimensions of tensor

 scalar.ndim

0

In [7]:
 # create a vector
 vector = tf.constant([10, 10])
 vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# check the dim of vector
vector.ndim

1

In [9]:
# create a Matrix
matrix = tf.constant([[10,10],
                      [10, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10,  7]], dtype=int32)>

In [10]:
  matrix.ndim

2

In [13]:
# create other matrix with fixed dtype
other_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float16) # specify the dtype param
other_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

In [14]:
# dim of other matrix
other_matrix.ndim

2

In [15]:
# Let's create a dimension

tensor = tf.constant([[[1, 2, 3, ], [4, 5, 6]],
                      [[6, 7, 8], [9, 8, 7]],
                      [[10, 11, 12], [13, 14, 15]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9,  8,  7]],

       [[10, 11, 12],
        [13, 14, 15]]], dtype=int32)>

In [17]:
# dim of tensor
tensor.ndim

3

Whats learnt so far
* Scalar: a single number
* Vector: a number with the direction
* Matrix : a 2-dim array of numbers
* Tensor: an n-dimensional array of numbers (0- dimensional tensor is Scalar, 1- dim tensor is vector)