<a href="https://colab.research.google.com/github/Harsha-7989/TensorFlow/blob/main/TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

  Introduction to Tensors
  * Getting infromation to tensors
  *  Manipulating tensors
  *  Tensors and Numpy
  * Using @tf.function (a way to speed up your regular python functions)
  * Using GPUs with Tensorflow (OR TPUs)


#**Introduction** to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [3]:
# Creating the Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
 # check the dimensions of tensor

 scalar.ndim

0

In [5]:
 # create a vector
 vector = tf.constant([10, 10])
 vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the dim of vector
vector.ndim

1

In [7]:
# create a Matrix
matrix = tf.constant([[10,10],
                      [10, 7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [10,  7]], dtype=int32)>

In [8]:
  matrix.ndim

2

In [9]:
# create other matrix with fixed dtype
other_matrix = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float16) # specify the dtype param
other_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)>

In [10]:
# dim of other matrix
other_matrix.ndim

2

In [11]:
# Let's create a dimension

tensor = tf.constant([[[1, 2, 3, ], [4, 5, 6]],
                      [[6, 7, 8], [9, 8, 7]],
                      [[10, 11, 12], [13, 14, 15]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 6,  7,  8],
        [ 9,  8,  7]],

       [[10, 11, 12],
        [13, 14, 15]]], dtype=int32)>

In [12]:
# dim of tensor
tensor.ndim

3

Whats learnt so far
* Scalar: a single number
* Vector: a number with the direction
* Matrix : a 2-dim array of numbers
* Tensor: an n-dimensional array of numbers (0- dimensional tensor is Scalar, 1- dim tensor is vector)

# Creating tensors with tf.variable()

In [14]:
# create the same tensor as above

changable_tensor = tf.Variable([10, 9])
unchangable_tensor = tf.constant([10, 9])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  9], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  9], dtype=int32)>)

In [20]:
# lets change one of the elemnts in changable tensor
changable_tensor[0].assign(9)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 9], dtype=int32)>

In [21]:
# lets change one of the elemnts in unchangable tensor
# unchangable_tensor[0].assign(9)
# unchangable_tensor
# output : AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Creating Random Tensors

 Random Tensors are tensors of some arbitary constants which contain the random numbers

In [26]:
 # create a two random(but the same) tensors
 random_1 = tf.random.Generator.from_seed(8) # set seed for reproducibility
 random_1 = random_1.normal(shape=(3, 2))
 random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.69211644,  0.84215707],
       [-0.06378496,  0.92800784],
       [-0.6039789 , -0.1766927 ]], dtype=float32)>

In [27]:
random_2 = tf.random.Generator.from_seed(8) # set seed for reproducibility
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.69211644,  0.84215707],
       [-0.06378496,  0.92800784],
       [-0.6039789 , -0.1766927 ]], dtype=float32)>

In [28]:
# are these equal
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

## shuffle the order of elements in a tensor

In [31]:
# shuffle a tensor(when you want to shuffle your data so your inherent order doesnt effect learning )
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim, not_shuffled

(2,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>)

In [33]:
# shuffle a non_suffled tensor

tf.random.shuffle(not_shuffled)

# it randomly shuffles the tensor along the first dimension

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [49]:
tf.random.shuffle(not_shuffled, seed = 42) # operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [51]:
# to get the same order again and again
tf.random.set_seed(42)#global seee
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>